apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
      - name: pytest-runner
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Never
  backoffLimit: 3
